apiVersion: apps/v1
kind: Deployment
metadata:
  name: diffing
  namespace: staging
spec:
  selector:
    matchLabels:
      app: diffing-server
  replicas: 2
  template:
    metadata:
      labels:
        app: diffing-server
    spec:
      containers:
      - name: processing
        image: envirodgi/processing:d4aabc09f3e52cee0ba7e0cbd3df5988e86b1b95
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: DIFFER_COLOR_INSERTION
          value: "#a1d76a"
        - name: DIFFER_COLOR_DELETION
          value: "#e8a4c8"
        - name: DIFFER_PARALLELISM
          value: "2"
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: diffing-secrets
              key: sentry_dsn
        - name: SENTRY_ENVIRONMENT
          value: "staging"
