apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: diffing
  namespace: staging
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: diffing-server
    spec:
      containers:
      - name: processing
        image: envirodgi/processing:85f75ff44ce11374f6d8b9a58e1da98da15b9a71
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: DIFFER_COLOR_INSERTION
          value: "#a1d76a"
        - name: DIFFER_COLOR_DELETION
          value: "#e8a4c8"
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: diffing-secrets
              key: sentry_dsn
        - name: SENTRY_ENVIRONMENT
          value: "staging"
