apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: staging
spec:
  selector:
    matchLabels:
      app: ui
  replicas: 2
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui 
        image: envirodgi/ui:3ab7f6704b1f2dac73a9c978b849afd419207de5
        imagePullPolicy: Always
        ports: 
        - containerPort: 3001
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3001
          initialDelaySeconds: 5
        env:
        - name: FORCE_SSL
          value: "true"
        - name: GOOGLE_DICTIONARY_SHEET_ID
          valueFrom:
            secretKeyRef:
              name: ui-secrets
              key: google_dictionary_sheet_id
        - name: GOOGLE_IMPORTANT_CHANGE_SHEET_ID
          valueFrom:
            secretKeyRef:
              name: ui-secrets
              key: google_important_change_sheet_id
        - name: GOOGLE_SERVICE_CLIENT_EMAIL
          valueFrom:
            secretKeyRef:
              name: ui-secrets
              key: google_service_client_email
        - name: GOOGLE_SHEETS_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: ui-secrets
              key: google_sheets_private_key
        - name: GOOGLE_TASK_SHEET_ID
          valueFrom:
            secretKeyRef:
              name: ui-secrets
              key:  google_task_sheet_id
        - name: WEB_MONITORING_DB_URL
          valueFrom:
            secretKeyRef:
              name: ui-secrets
              key:  web_monitoring_db_url
        - name: INCREMENTAL_UPDATE
          value: "1"
