apiVersion: v1
kind: Service
metadata:
  name: diffing
  namespace: production
spec:
  selector:
    app: diffing-server
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
