---
# EXAMPLE SECRETS FILE
# The real versions of this file are kept in a separate, secure repository. It
# contains any sensitive values (usually credentials) needed by a deployment.
# We usually have one secrets file per deployment per namespace, e.g:
#   - secrets.api.production.yaml
#   - secrets.diffing.production.yaml
#   - secrets.ui.production.yaml
#   - secrets.api.staging.yaml
#   - secrets.diffing.staging.yaml
#   - secrets.ui.staging.yaml

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: app-secrets
  namespace: production

# String data for easy reading/editing
stringData:
  aws_access_key_id: "ABCXYZ"
  aws_secret_access_key: "XYZABC"
  database_rds: "postgres://user:pass@rds:5432/web_monitoring_db"
  host_url: "https://api.monitoring.envirodatagov.org/"
  postmark_api_token: "XXXX"
  secret_key_base: "XXXX"
  sentry_dsn: "https://abc:xyz@sentry.io/xxx"
  redis_cache_url: "redis://abc:xyz@redis_cache.address:1234/0"

# Binary Data for things that don't fit nicely into plain text
data:
  # Base64 encoding this so we don't have to worry about escaping the contents.
  token_private_key: WE9ZQjteV1Q3cVBvVGhHdTg1ZWpWYEtHUDh5W2RzbjR4YjtKbk9cZVdac2NjZmo1ak1zR3REPTlqOkEwWFdORz9GeUJ0VkpoV1J1eVhwRUs/Vj43P3dJTXltWWJfYGxJMDUwbUhccFVWWnRZbTU7SkdFWkA3X2Nldzg7Mlc0dUNAY0d3ODdhNWJBO1RYc1xBWDRgZVBkdzNYZkZFTWRzQFpjcT1qbWJXa3NwW0RHX09XMU5yX0ZjR05BM1AyR3YwPTxYeDxeP0k+YkRTTGpzeGFGPl5RYW9mWUx4SnhqcUtYTGRoaHY1MkUyUjVrPHE7dF09NFtHTXVlQkQ4NFJ0bg==
