apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: diffing
  namespace: production
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: diffing-server
    spec:
      containers:
      - name: processing
        image: envirodgi/processing:f4c2f417ba11a9797f3a3276fe65c3179e0d804c
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
        resources:
          requests:
            memory: "265Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: DIFFER_COLOR_INSERTION
          value: "#a1d76a"
        - name: DIFFER_COLOR_DELETION
          value: "#e8a4c8"
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: diffing-secrets
              key: sentry_dsn
